export const tracks = [
  // ===== SHORT =====
  {
    id: 1,
    title: "珍パンジー",
    type: "short",
    filename: "short_chinpanji",
    src: "/short/short_chinpanji.mp3",
    duration: "0:53",
    tags: ["女性", "ネタ", "楽しい"],
  },
  {
    id: 2,
    title: "お前の母ちゃんでべそ",
    type: "short",
    filename: "short_debeso1",
    src: "/short/short_debeso1.mp3",
    duration: "0:47",
    tags: ["男性", "ネタ", "楽しい"],
  },
  {
    id: 3,
    title: "お前の母ちゃんでべそ (Remix)",
    type: "short",
    filename: "short_debeso2",
    src: "/short/short_debeso2.mp3",
    duration: "1:16",
    tags: ["女性", "ネタ", "感動", "全米が泣いた"],
  },
  {
    id: 4,
    title: "ゴリラのマーチ",
    type: "short",
    filename: "short_gorila",
    src: "/short/short_gorila.mp3",
    duration: "0:56",
    tags: ["女性", "ネタ", "楽しい"],
  },
  {
    id: 5,
    title: "わたしは可愛い☆彡",
    type: "short",
    filename: "short_kawaii",
    src: "/short/short_kawaii.mp3",
    duration: "1:40",
    tags: ["女性", "アイドル", "ポップ", "恋愛"],
  },
  {
    id: 6,
    title: "I LOVE 筋肉",
    type: "short",
    filename: "short_kinniku",
    src: "/short/short_kinniku.mp3",
    duration: "1:13",
    tags: ["女性", "ネタ", "アイドル", "筋肉"],
  },
  {
    id: 7,
    title: "ピクセルジャンプの冒険",
    type: "short",
    filename: "short_mario",
    src: "/short/short_mario.mp3",
    duration: "1:40",
    tags: ["男性", "ネタ", "ゲーム音楽", "マリオ"],
  },
  {
    id: 8,
    title: "ピルリルポンポン",
    type: "short",
    filename: "short_piruriruponpon",
    src: "/short/short_piruriruponpon.mp3",
    duration: "1:42",
    tags: ["女性", "アイドル", "ポップ", "リラックス"],
  },
  {
    id: 9,
    title: "秋刀魚の数え唄",
    type: "short",
    filename: "short_sanma",
    src: "/short/short_sanma.mp3",
    duration: "0:46",
    tags: ["女性", "ネタ", "教育番組？"],
  },
  {
    id: 10,
    title: "Sugoi・Erai☆彡",
    type: "short",
    filename: "short_sugoierai",
    src: "/short/short_sugoierai.mp3",
    duration: "1:19",
    tags: ["女性", "アイドル", "ポップ", "前向き"],
  },
  {
    id: 11,
    title: "つまんない",
    type: "short",
    filename: "short_tsumannai",
    src: "/short/short_tsumannai.mp3",
    duration: "1:39",
    tags: ["女性", "ロック"],
  },
  {
    id: 12,
    title: "宇宙戦艦ヴァルキュリア",
    type: "short",
    filename: "short_uchuanime",
    src: "/short/short_uchuanime.mp3",
    duration: "1:34",
    tags: ["女性", "アニメOP"],
  },

  // ===== LONG =====
  {
    id: 101,
    title: "終わりの静寂",
    type: "long",
    filename: "long_owarinoshijima",
    src: "/long/long_owarinoshijima.mp3",
    duration: "3:28",
    tags: ["女性", "切ない", "静か"],
  },
  {
    id: 102,
    title: "遥かな君へ",
    type: "long",
    filename: "long_harukanakimie",
    src: "/long/long_harukanakimie.mp3",
    duration: "4:18",
    tags: ["女性", "切ない", "静か", "強い"],
  },
  {
    id: 103,
    title: "エンドロール",
    type: "long",
    filename: "long_endroll",
    src: "/long/long_endroll.mp3",
    duration: "5:15",
    tags: ["男性", "恋愛", "切ない", "女性視点"],
  },
  {
    id: 104,
    title: "夢枕",
    type: "long",
    filename: "long_yumemakura",
    src: "/long/long_yumemakura.mp3",
    duration: "4:24",
    tags: ["女性", "切ない", "柔らかい"],
  },
  {
    id: 105,
    title: "夕立ちのあとで",
    type: "long",
    filename: "long_yuudachinoatode",
    src: "/long/long_yuudachinoatode.mp3",
    duration: "4:47",
    tags: ["女性", "切ない", "優しい"],
  },
  {
    id: 106,
    title: "あかきゆめみし",
    type: "long",
    filename: "long_akakiyumemishi",
    src: "/long/long_akakiyumemishi.mp3",
    duration: "4:42",
    tags: ["女性", "劇用曲", "切ない", "悲恋", "悲劇"],
  },
  {
    id: 107,
    title: "猫みたいな君",
    type: "long",
    filename: "long_nekomitainakimi",
    src: "/long/long_nekomitainakimi.mp3",
    duration: "4:27",
    tags: ["男性", "切ない", "恋愛", "別れ"],
  },
  {
    id: 108,
    title: "だいじょうぶ",
    type: "long",
    filename: "long_daijoubu",
    src: "/long/long_daijoubu.mp3",
    duration: "3:19",
    tags: ["女性", "明るい", "ポップ"],
  },
  {
    id: 109,
    title: "ありがとう",
    type: "long",
    filename: "long_arigatou",
    src: "/long/long_arigatou.mp3",
    duration: "4:38",
    tags: ["女性", "優しい", "穏やか"],
  },
  {
    id: 110,
    title: "あの頃のままで",
    type: "long",
    filename: "long_anokoronomamade",
    src: "/long/long_anokoronomamade.mp3",
    duration: "4:01",
    tags: ["女性", "明るい", "優しい", "懐かしい"],
  },
  {
    id: 111,
    title: "黒き月",
    type: "long",
    filename: "long_kurokitsuki",
    src: "/long/long_kurokitsuki.mp3",
    duration: "3:26",
    tags: ["男女", "オペラ", "怪しい", "激しい"],
  },

  // ===== ENGLISH（新規） =====
  {
    id: 201,
    title: "Cosmic Conversations",
    type: "english",
    filename: "eng_Cosmic",
    src: "/English/eng_Cosmic.mp3",
    duration: "4:12",
    tags: ["女性", "爽やか", "しっとり"],
  },
  {
    id: 202,
    title: "Eclipse of Love",
    type: "english",
    filename: "eng_Eclipse",
    src: "/English/eng_Eclipse.mp3",
    duration: "3:53",
    tags: ["女性", "ダーク", "宗教的", "合唱"],
  },
  {
    id: 203,
    title: "Christmas Miracle",
    type: "english",
    filename: "eng_Christmas",
    src: "/English/eng_Christmas.mp3",
    duration: "3:47",
    tags: ["男性", "クリスマス", "優しい", "ムード"],
  },

  // ===== INST（新規） =====
  {
    id: 301,
    title: "独りの穏やかな朝",
    type: "inst",
    filename: "inst_01",
    src: "/inst/inst_01.mp3",
    duration: "3:59",
    tags: ["ピアノソロ", "穏やか", "爽やか", "寂しい"],
  },
  {
    id: 302,
    title: "夢から覚めて",
    type: "inst",
    filename: "inst_02",
    src: "/inst/inst_02.mp3",
    duration: "3:44",
    tags: ["ピアノソロ", "穏やか", "優しい", "切ない"],
  },
  {
    id: 303,
    title: "憧れ",
    type: "inst",
    filename: "inst_03",
    src: "/inst/inst_03.mp3",
    duration: "2:49",
    tags: ["ピアノソロ", "穏やか", "華やか"],
  },
  {
    id: 304,
    title: "消えた約束",
    type: "inst",
    filename: "inst_04",
    src: "/inst/inst_04.mp3",
    duration: "3:58",
    tags: ["ピアノソロ", "ノスタルジック"],
  },
  {
    id: 305,
    title: "卒業（別れの季節）",
    type: "inst",
    filename: "inst_05",
    src: "/inst/inst_05.mp3",
    duration: "4:09",
    tags: ["ピアノ", "寂しい", "感動"],
  },
  {
    id: 306,
    title: "穏やかでグッドエンド",
    type: "inst",
    filename: "inst_06",
    src: "/inst/inst_06.mp3",
    duration: "3:12",
    tags: ["ピアノソロ", "穏やか", "爽やか"],
  },
  {
    id: 307,
    title: "悲しみの中で",
    type: "inst",
    filename: "inst_07",
    src: "/inst/inst_07.mp3",
    duration: "3:59",
    tags: ["ピアノソロ", "悲しい", "切ない"],
  },
  {
    id: 308,
    title: "無くした心を求めて",
    type: "inst",
    filename: "inst_08",
    src: "/inst/inst_08.mp3",
    duration: "4:24",
    tags: ["ピアノ", "ヴァイオリン", "悲しい", "切ない"],
  },
  {
    id: 309,
    title: "Shadows Rising",
    type: "inst",
    filename: "inst_09",
    src: "/inst/inst_09.mp3",
    duration: "3:06",
    tags: ["女性声", "悲しい", "ホラー", "合唱"],
  },
];
