export type Track = {
  id: number;
  title: string;
  type: "short" | "long";
  src: string;
  duration: string; // "0:53" のような表示用
  tags: string[];   // 「女性」「ネタ」「楽しい」など
};

export const tracks: Track[] = [
  // ===== SHORT SONGS =====
  {
    id: 1,
    title: "珍パンジー",
    type: "short",
    src: "/short/short_chinpanji.mp3",
    duration: "0:53",
    tags: ["女性", "ネタ", "楽しい"],
  },
  {
    id: 2,
    title: "お前の母ちゃんでべそ",
    type: "short",
    src: "/short/short_debeso1.mp3",
    duration: "0:47",
    tags: ["男性", "ネタ", "楽しい"],
  },
  {
    id: 3,
    title: "お前の母ちゃんでべそ (Remix)",
    type: "short",
    src: "/short/short_debeso2.mp3",
    duration: "1:16",
    tags: ["女性", "ネタ", "感動", "全米が泣いた"],
  },
  {
    id: 4,
    title: "ゴリラのマーチ",
    type: "short",
    src: "/short/short_gorila.mp3",
    duration: "0:56",
    tags: ["女性", "ネタ", "楽しい"],
  },
  {
    id: 5,
    title: "わたしは可愛い☆彡",
    type: "short",
    src: "/short/short_kawaii.mp3",
    duration: "1:40",
    tags: ["女性", "アイドル", "ポップ", "恋愛"],
  },
  {
    id: 6,
    title: "I LOVE 筋肉",
    type: "short",
    src: "/short/short_kinniku.mp3",
    duration: "1:13",
    tags: ["女性", "ネタ", "アイドル", "筋肉"],
  },
  {
    id: 7,
    title: "ピクセルジャンプの冒険",
    type: "short",
    src: "/short/short_mario.mp3",
    duration: "1:40",
    tags: ["男性", "ネタ", "ゲーム音楽", "マリオ"],
  },
  {
    id: 8,
    title: "ピルリルポンポン",
    type: "short",
    src: "/short/short_piruriruponpon.mp3",
    duration: "1:42",
    tags: ["女性", "アイドル", "ポップ", "リラックス"],
  },
  {
    id: 9,
    title: "秋刀魚の数え唄",
    type: "short",
    src: "/short/short_sanma.mp3",
    duration: "0:46",
    tags: ["女性", "ネタ", "教育番組？"],
  },
  {
    id: 10,
    title: "Sugoi・Erai☆彡",
    type: "short",
    src: "/short/short_sugoierai.mp3",
    duration: "1:19",
    tags: ["女性", "アイドル", "ポップ", "前向き"],
  },
  {
    id: 11,
    title: "つまんない",
    type: "short",
    src: "/short/short_tsumannai.mp3",
    duration: "1:39",
    tags: ["女性", "ロック"],
  },
  {
    id: 12,
    title: "宇宙戦艦ヴァルキュリア",
    type: "short",
    src: "/short/short_uchuanime.mp3",
    duration: "1:34",
    tags: ["女性", "アニメOP"],
  },

  // ===== LONG SONGS =====
  {
    id: 13,
    title: "終わりの静寂",
    type: "long",
    src: "/long/long_owarinoshijima.mp3",
    duration: "3:28",
    tags: ["女性", "切ない", "静か"],
  },
  {
    id: 14,
    title: "遥かな君へ",
    type: "long",
    src: "/long/long_harukanakimie.mp3",
    duration: "4:18",
    tags: ["女性", "切ない", "静か", "強い"],
  },
  {
    id: 15,
    title: "エンドロール",
    type: "long",
    src: "/long/long_endroll.mp3",
    duration: "5:15",
    tags: ["男性", "恋愛", "切ない", "女性視点"],
  },
  {
    id: 16,
    title: "夢枕",
    type: "long",
    src: "/long/long_yumemakura.mp3",
    duration: "4:24",
    tags: ["女性", "切ない", "柔らかい"],
  },
  {
    id: 17,
    title: "夕立ちのあとで",
    type: "long",
    src: "/long/long_yuudachinoatode.mp3",
    duration: "4:47",
    tags: ["女性", "切ない", "優しい"],
  },
  {
    id: 18,
    title: "あかきゆめみし",
    type: "long",
    src: "/long/long_akakiyumemishi.mp3",
    duration: "4:42",
    tags: ["女性", "劇用曲", "切ない", "悲恋", "悲劇"],
  },
  {
    id: 19,
    title: "猫みたいな君",
    type: "long",
    src: "/long/long_nekomitainakimi.mp3",
    duration: "4:27",
    tags: ["男性", "切ない", "恋愛", "別れ"],
  },
  {
    id: 20,
    title: "だいじょうぶ",
    type: "long",
    src: "/long/long_daijoubu.mp3",
    duration: "3:19",
    tags: ["女性", "明るい", "ポップ"],
  },
  {
    id: 21,
    title: "ありがとう",
    type: "long",
    src: "/long/long_arigatou.mp3",
    duration: "4:38",
    tags: ["女性", "優しい", "穏やか"],
  },
  {
    id: 22,
    title: "あの頃のままで",
    type: "long",
    src: "/long/long_anokoronomamade.mp3",
    duration: "4:01",
    tags: ["女性", "明るい", "優しい", "懐かしい"],
  },
  {
    id: 23,
    title: "黒き月",
    type: "long",
    src: "/long/long_kurokitsuki.mp3",
    duration: "3:26",
    tags: ["男女", "オペラ", "怪しい", "激しい"],
  },
];
